% -----------------------------------------------------------------------------
% LaTeX class for the BSc/Msc thesis at the Departments of Earth
% and Planetary Sciences, ETH Zurich.
% 
% Jochen Wuttke <jwuttke@ethz.ch>
%
% THIS IS NOT AN OFFICIAL ETHZ CLASS. USE AT YOUR OWN RISK.
%
% -----------------------------------------------------------------------------
%%
%% This file is 'eapsthesis.cls'
%% 
%% It may be distributed and/or modified under the
%% conditions of the LaTeX Project Public License, either version 1.3c
%% of this license or (at your option) any later version.
%% The latest version of this license is in
%%    http://www.latex-project.org/lppl.txt
%% and version 1.3c or later is part of all distributions of LaTeX
%% version 2005/12/01 or later.

%%% identification
\NeedsTeXFormat{LaTeX2e}[1995/12/01]
\ProvidesClass{thesis}[2026/01/17 v. 0.1 %
 ETH D-EAPS thesis class]
%%% initial code
\RequirePackage{xifthen}
